sudo:
  false

language:
  php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - 'master'

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors
