sudo: false

language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--dev"

addons:
  # sonarcloud analysis with the travis plugin, see https://docs.travis-ci.com/user/sonarcloud/
  sonarcloud:
    organization: "ar2labs"
    token:
      secure: $SONAR_TOKEN

before_script:
  - composer self-update
  - composer require --dev phpunit/phpunit:^8.5 --no-interaction --no-suggest --no-progress
  - composer require --dev phpstan/phpstan:^0.12 --no-interaction --no-suggest --no-progress
  - composer require --dev friendsofphp/php-cs-fixer:^2.16 --no-interaction --no-suggest --no-progress
  - composer require --dev php-coveralls/php-coveralls:^2.2 --no-interaction --no-suggest --no-progress
  - composer install --no-interaction --no-suggest --no-progress

script:
  - composer check-all

after_success:
  - vendor/bin/php-coveralls --coverage_clover=coverage-report.clover -v
