sudo:
  false

language:
  php

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - php -m
  - composer self-update
  - composer install --no-interaction --prefer-source
  
install:
  - sudo apt install -y --force-yes php-cmath

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors
