sudo:
  false

language:
  php

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --config=php_cs.dist --no-interaction
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors
  - vendor/bin/phpstan analyse src tests --level=max --no-progress