sudo: false

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--dev"

addons:
  # sonarcloud analysis with the travis plugin, see https://docs.travis-ci.com/user/sonarcloud/
  sonarcloud:
    organization: "ar2labs"
    token:
      secure: $SONAR_TOKEN

before_script:
  - composer self-update
  - composer require --dev phpunit/phpunit:^7.5 --no-interaction --no-suggest --no-progress
  - composer require --dev phpstan/phpstan-shim:^0.11 --no-interaction --no-suggest --no-progress
  - composer require --dev friendsofphp/php-cs-fixer:^2.15 --no-interaction --no-suggest --no-progress
  - composer require --dev php-coveralls/php-coveralls:^2.1 --no-interaction --no-suggest --no-progress
  - composer install --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/php-cs-fixer fix --config=php_cs.dist --no-interaction
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage-report.clover --log-junit=test-report.xml --colors
  - vendor/bin/phpstan analyse src tests --level=max --no-progress
  # sonar only on non-PRs & branch master
  - 'if [[ ${TRAVIS_PULL_REQUEST} == "false" && ${TRAVIS_BRANCH} == "master" ]]; then sonar-scanner; fi'

after_success:
  - vendor/bin/php-coveralls --coverage_clover=coverage-report.clover -v
