sudo: false

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

addons:
  # sonarcloud analysis with the travis plugin, see https://docs.travis-ci.com/user/sonarcloud/
  sonarcloud:
    organization: "ar2labs"
    token:
      secure: $SONAR_TOKEN

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/php-cs-fixer fix --config=php_cs.dist --no-interaction
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors
  - vendor/bin/phpstan analyse src tests --level=max --no-progress
  # sonar only on non-PRs & branch master
  - 'if [[ ${TRAVIS_PULL_REQUEST} == "false" && ${TRAVIS_BRANCH} == "master" ]]; then sonar-scanner; fi'
