sonar.projectKey=ar2labs_wiring
sonar.organization=ar2labs
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml
